# only build production branches
branches:
  only:
    - /^\d+(?:\.\d+)*$/

# build config
language: php
php:
  - 5.5
before_install:
  - composer self-update
before_script:
  - composer install 
script:
  - ./vendor/bin/phpunit
